## Contd .. Functions

In [1]:
#Q Write a funciton, sqr_c(), that
# 1. Receives a numerical list
# 2. Squares each element
# 3. Returns the result
# 4. The caller should NOT see the change in the original list

In [2]:
def sqr_c(a):
    b = a.copy()
    for i in range(len(b)):
        b[i] *= b[i]
    return b
        
l = [1,2,3]
m = sqr_c(l)
print(l)
print(m)

[1, 2, 3]
[1, 4, 9]


## Shallow copy vs Deep copy

Shallow copy only does one layer of copying. Deep copy does recursive copying and any change in sub-elements also won't be carried forwarded to original data

In [3]:
import copy

# initializing list 1
l1 = [1, 2, [3,5], 4]
 
# using copy to shallow copy
l2 = copy.copy(l1)

# original elements of list
print ("The original elements before shallow copying")
for i in range(0,len(l1)):
    print (l1[i],end=" ")
print("\r")
 
# adding and element to new list
l2[2][0] = 7  # ==> here we are updating the sub-ele of a list
l2[3] = 10 # ==> we are updating ele of a list
l2.append(20)

# checking if change is reflected
print ("The shallow copied list elements after udpating")
for i in range(0,len(l2)):
    print (l2[i],end=" ")
print("\r")

# checking if change is reflected
print ("The original elements after updating shallow copied list")
for i in range(0,len( l1)):
    print (l1[i],end=" ")

The original elements before shallow copying
1 2 [3, 5] 4 
The shallow copied list elements after udpating
1 2 [7, 5] 10 20 
The original elements after updating shallow copied list
1 2 [7, 5] 4 

In [4]:
# initializing list 1
l1 = [1, 2, [3,5], 4]
 
# using copy to shallow copy
l2 = copy.deepcopy(l1)

# original elements of list
print ("The original elements before shallow copying")
for i in range(0,len(l1)):
    print (l1[i],end=" ")
print("\r")
 
# adding and element to new list
l2[2][0] = 7  # ==> here we are updating the sub-ele of a list
l2[3] = 10 # ==> we are updating ele of a list
l2.append(20)

# checking if change is reflected
print ("The deep copied list elements after udpating")
for i in range(0,len(l2)):
    print (l2[i],end=" ")
print("\r")

# checking if change is reflected
print ("The original elements after updating deep copied list")
for i in range(0,len( l1)):
    print (l1[i],end=" ")

The original elements before shallow copying
1 2 [3, 5] 4 
The deep copied list elements after udpating
1 2 [7, 5] 10 20 
The original elements after updating deep copied list
1 2 [3, 5] 4 

## Classes and Objects

- Variables : general data variables which store some kind of data
- Methods : They are similar to function with parameters and return but the scope (the ability to use them) is limited
- Object : It is a collection of data variables and methods explained above
- Class : It is a blueprint for the object i.e. it has logic written for all the variables and methods and it controls the flow of the execution
- As many cars can be made from car's blueprint, we can create many objects from a class. An object can also be callas as an instance of class.
- Instantiation: The process of creating an object by calling the class is called instantiation

In [5]:
# typical structure of a class
class ClassName:  
    # list of python class variables  
    # python class constructor  
    # python class method definitions
    # the below line is optional
    pass # ==> implies do nothing

In [6]:
class Person:
    '''
    This has the skeleton of a simple person class
    '''
    #initializing the variables  
    name = ""
      
    #defining constructor  
    def __init__(self, personName, personAge):  
        self.name = personName  
        self.age = personAge  
  
    #defining class methods  
    def showName(self):  
        print(self.name)  
  
    def showAge(self):  
        print(self.age)
    
    def intro(self):
        '''
        This function is used to create a introduction statement using both name and age of the person
        '''
        print("{}, aged {} years is one of the ethusiastic members of MCDB 170 class !!!".format(self.name, self.age))
          
    #end of the class definition  

Class functions that begin with double underscore __ are called special functions as they have special meaning.

The $__init__()$ function is called constructor which gets called whenever a new object of that class is instantiated.

In [7]:
#Create an object of the class  
person1 = Person("John", 23)  
#Create another object of the same class  
person2 = Person("Anne", 102)  
#call member methods of the objects  
person1.showAge()  
person2.showName()
person1.intro()

23
Anne
John, aged 23 years is one of the ethusiastic members of MCDB 170 class !!!


In [8]:
# other way of accessing name, but we cant write info everytime as its code duplication
person1.name

'John'

In [9]:
# trying to update the age
person1.age = 30
person1.intro()

John, aged 30 years is one of the ethusiastic members of MCDB 170 class !!!


In [10]:
# trying to create a new variable
person1.department = "MCDB"

In [11]:
print(person1.department)
print(person2.department)

MCDB


AttributeError: 'Person' object has no attribute 'department'

In [15]:
# deleting a class variable
print(person2.age)
del person2.age
print(person2.age)

102


AttributeError: 'Person' object has no attribute 'age'

In [12]:
print(person1.__doc__)


    This has the skeleton of a simple person class
    


In [13]:
person1.__class__

__main__.Person

In [14]:
person1?

Type:        Person
String form: <__main__.Person object at 0x7f7c8a33b700>
Docstring:   This has the skeleton of a simple person class


In [20]:
person1.intro?

Signature: person1.intro()
Docstring: This function is used to create a introduction statement using both name and age of the person
File:      ~/Downloads/Course Contents/Fall 2022/MCDB 170/<ipython-input-10-50556d65dbd3>
Type:      method


In [16]:
person1.intro??

Signature: person1.intro()
Source:   
    def intro(self):
        '''
        This function is used to create a introduction statement using both name and age of the person
        '''
        print("{}, aged {} years is one of the ethusiastic members of MCDB 170 class !!!".format(self.name, self.age))
File:      /tmp/ipykernel_107/537578347.py
Type:      method


In [17]:
class TrafficLight:
    '''This is an class traffic lights'''
    # Class variable
    traffic_light_address = 'UCSB Campus Beachpoint'
    color = ''

    def __init__(self, color):
        # Instance variable assigned inside the class constructor
        self.color = color

    def action(self):
        if self.color=='red':
            # Instance variable assigned inside a class method
            self.next_color = 'yellow'
            print('Stop & wait')
        elif self.color=='yellow':
            self.next_color = 'green'
            print('Prepare to stop')
        elif self.color=='green':
            self.next_color = 'red'
            print('Go')
        else:
            self.next_color = 'Whisky'
            print('Stop drinking :P')

# Creating class objects
for c in ['red', 'yellow', 'green', 'tennesse honey']:
    c = TrafficLight(c)
    print(c.traffic_light_address)
    print(c.color)
    c.action()
    print(c.next_color)
    print('\r')

UCSB Campus Beachpoint
red
Stop & wait
yellow

UCSB Campus Beachpoint
yellow
Prepare to stop
green

UCSB Campus Beachpoint
green
Go
red

UCSB Campus Beachpoint
tennesse honey
Stop drinking :P
Whisky



- Class variables: assigned in the class declaration but outside any method definition (including the class constructor). They are related to all object instances of that class.
- Instance variables: assigned inside a class method or constructor definition. They are unique to each object instance of that class.

## Importing
- Library : Collection of classes
- Reusability of same piece of logic at multiple places

In [18]:
from custom_class import TrafficLight
from custom_class import *
from custom_class import TrafficLight as tada

## Debugging

In [19]:
# Code to compute the number of vowels in a text

text = "Undergrad Biology"
# The ideal answer should be 5
vowels = 0
for i in text:
    if(i=='a' or i=='e' or i=='l' or i=='o' or i!='u' or i=='A' or i=='E' or i=='I' or i=='O' or i=='U'):
        vowels += 1
# print("Number of vowels are:", vowels)

In [35]:
# uncomment the below line to install ipdb
# !pip install ipdb

In [33]:
import ipdb
# ipdb.set_trace()

In [21]:
# Funciton to compute sum of digits of a number

number = 5279

def num_sum(n):
    ans = 0
    while(n):
        # computing the remainder
        temp = n%10
        # adding it to the answer
        ans = ans - n%10
        # dividing the number by 10
        n/=10
    return ans

print(num_sum(number))

-25.555555555555536


## Recursion

In [22]:
# Function to compute factorial of a number
# F(n) = n * (n-1) * (n-2) * (n-3) .... * 1

def fact(n):
    if (n == 0):
        return 1
    return n * fact(n-1)

print(fact(2))
print(fact(3))
print(fact(5))

2
6
120


## Numpy

In [23]:
import numpy as np

In [24]:
np.array([1, 2, 3])

array([1, 2, 3])

In [25]:
np.mean([1, 2, 3])

2.0

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.power(2, 3)

8

In [28]:
np.arange(4)

array([0, 1, 2, 3])

## Random

In [29]:
import random

my_passwd = random.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789*$@#%_-!',k=16)
my_passwd = ''.join(my_passwd)
print(my_passwd)

@t$SRwNIW$cnUrjf


In [30]:
random.choices([1, 2, 3, 4, 5, 6, 7], k=2)

[1, 5]

In [31]:
# random.choices?