#### Problem 1 solution

In [4]:
# Change the following function.

# DO NOT CHANGE THE FUNCTION NAME AND ARGUMENTS!!!

import numpy as np


def get_cov( x, y ):
    return ((x-x.mean())*(y-y.mean())).sum()/x.size


In [5]:
# The following code is provided for your test.
# You can modify it as you want, to test your function.

np.random.seed(100)
x = np.random.normal(size=[100])
y = np.random.normal(size=[100])

print(get_cov(x,y))

-0.16698940055760494


---

#### Problem 2 solution

In [6]:
# Complete the following function.

# DO NOT CHANGE THE FUNCTION NAME AND ARGUMENTS!!!

import numpy as np
def get_covmat( x ):
    m,n = x.shape
    covmat = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            covmat[i,j] = get_cov( x[:,i], x[:,j])
    
    return covmat
    

In [7]:
# The following code is provided for your test.
# You can modify it as you want, to test your function.

# Iris data. See https://archive.ics.uci.edu/ml/datasets/Iris
x = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
print(get_covmat(x))

[[ 0.68112222 -0.03900667  1.26519111  0.51345778]
 [-0.03900667  0.18675067 -0.319568   -0.11719467]
 [ 1.26519111 -0.319568    3.09242489  1.28774489]
 [ 0.51345778 -0.11719467  1.28774489  0.57853156]]


---

#### Problem 3 solution

In [8]:
# Complete the following function.

# DO NOT CHANGE THE FUNCTION NAME AND ARGUMENTS!!!

import numpy as np
def get_corrmat( x ):
    m,n = x.shape
    corrmat = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            corrmat[i,j] = get_cov( x[:,i], x[:,j]) / x[:,i].std() / x[:,j].std()
    
    return corrmat
    

In [10]:
# The following code is provided for your test.
# You can modify it as you want, to test your function.

x = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
print(get_corrmat(x))

[[ 1.         -0.10936925  0.87175416  0.81795363]
 [-0.10936925  1.         -0.4205161  -0.35654409]
 [ 0.87175416 -0.4205161   1.          0.9627571 ]
 [ 0.81795363 -0.35654409  0.9627571   1.        ]]
